discord:
  default_voice_channel: "ğ­ğ¡ğ ğ›ğšğ«"
  continuous_listen:
    activation_phrase: "bartender"
    recording_duration: 10
    pause_duration: 0.1
    sample_rate: 16000

openai:
  assistant:
    id: ""
    name: "Binkins"
  chat: 
    model: "gpt-4o-mini"
    temperature: 1.0
  voice: 
    model: "whisper-1"
    tts_voice: "nova"
    tts_model: "tts-1-hd"